name: PR Test
on:
  pull_request:
    branches: ['*']
    
jobs:
  pr-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20.11

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
     
      - name: Install dependencies
        run: pnpm install

      - name: Build Test
        run: pnpm build

      - name: Unit Test
        run: pnpm test

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

      
